// @generated by sdk/scripts/gen-parity-vectors.ts -- DO NOT EDIT.
// Cross-chain parity vectors for bosphor_commitment_codec.
use bosphor_commitment_codec::{decode, derive_intent_id, encode, Commitment, DecodeError};

struct V {
    blob_id: &'static str,
    size: u32,
    encoding_type: u8,
    storage_epochs: u32,
    deadline: u64,
    sender: &'static str,
    nonce: u64,
    commitment: &'static str,
    intent_id: &'static str,
}

const VECTORS: &[V] = &[
    V {
        blob_id: "0000000000000000000000000000000000000000000000000000000000000000",
        size: 0,
        encoding_type: 0,
        storage_epochs: 0,
        deadline: 0,
        sender: "0000000000000000000000000000000000000000000000000000000000000000",
        nonce: 0,
        commitment: "0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        intent_id: "a4f556b8070855da3e9bfc0116ab844ef964254b9516f31df26d980ad8a6b74a",
    },
    V {
        blob_id: "0000000000000000000000000000000000000000000000000000000000000000",
        size: 0,
        encoding_type: 0,
        storage_epochs: 5,
        deadline: 0,
        sender: "0000000000000000000000000000000000000000",
        nonce: 0,
        commitment: "0100000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000",
        intent_id: "77d74d8839cfef65e97c4619989a5cd3ffb1b8b0e142825b8270e1bf8aded8c7",
    },
    V {
        blob_id: "abababababababababababababababababababababababababababababababab",
        size: 1024,
        encoding_type: 1,
        storage_epochs: 5,
        deadline: 1760000000,
        sender: "00112233445566778899aabbccddeeff00112233",
        nonce: 7,
        commitment: "01abababababababababababababababababababababababababababababababab0000040001000000050000000068e77800",
        intent_id: "7827b0f7e14c906b545f8bc961cc4ccad1f73ba2b68461b12df0a49fa8f6bb25",
    },
    V {
        blob_id: "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
        size: 1,
        encoding_type: 2,
        storage_epochs: 10,
        deadline: 1234567890,
        sender: "cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe",
        nonce: 1,
        commitment: "01deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef00000001020000000a00000000499602d2",
        intent_id: "d992b1e321ffe9439081c607dfe780265eb9bf2e185a28b6e120876fe25bec47",
    },
    V {
        blob_id: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        size: 4294967295,
        encoding_type: 255,
        storage_epochs: 4294967295,
        deadline: 18446744073709551615,
        sender: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        nonce: 18446744073709551615,
        commitment: "01ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        intent_id: "6acabe660433db2f3c7e16b0a65e673cfcd59b0a427c3ba0f85e72571cc8129c",
    },
];

// (name, version byte, full-length commitment hex) that decode must reject.
const INVALID_VECTORS: &[(&str, u8, &str)] = &[
    ("unsupported_version_0", 0, "00abababababababababababababababababababababababababababababababab0000040001000000050000000068e77800"),
    ("unsupported_version_2", 2, "02abababababababababababababababababababababababababababababababab0000040001000000050000000068e77800"),
];

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap())
        .collect()
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

#[test]
fn parity_vectors_match() {
    for v in VECTORS {
        let mut blob_id = [0u8; 32];
        blob_id.copy_from_slice(&unhex(v.blob_id));
        let c = Commitment {
            blob_id,
            size: v.size,
            encoding_type: v.encoding_type,
            storage_epochs: v.storage_epochs,
            deadline: v.deadline,
        };
        assert_eq!(hex(&encode(&c)), v.commitment, "commitment mismatch");
        assert_eq!(
            hex(&derive_intent_id(&c, &unhex(v.sender), v.nonce)),
            v.intent_id,
            "intentId mismatch"
        );
    }
}

#[test]
fn invalid_versions_are_rejected() {
    for (name, version, commitment) in INVALID_VECTORS {
        assert_eq!(
            decode(&unhex(commitment)),
            Err(DecodeError::UnsupportedVersion(*version)),
            "decode must reject {}",
            name
        );
    }
}
