// @generated by sdk/scripts/gen-parity-vectors.ts -- DO NOT EDIT.
// Cross-chain parity vectors for bosphor_commitment_codec.
use bosphor_commitment_codec::{derive_intent_id, encode, Commitment};

struct V {
    blob_id: &'static str,
    size: u32,
    encoding_type: u8,
    storage_epochs: u32,
    deadline: u64,
    sender: &'static str,
    nonce: u64,
    commitment: &'static str,
    intent_id: &'static str,
}

const VECTORS: &[V] = &[
    V {
        blob_id: "0000000000000000000000000000000000000000000000000000000000000000",
        size: 0,
        encoding_type: 0,
        storage_epochs: 0,
        deadline: 0,
        sender: "0000000000000000000000000000000000000000000000000000000000000000",
        nonce: 0,
        commitment: "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        intent_id: "496e418294117864002a95f894a01c9cc414c86e17325489a5ea2f0eef181967",
    },
    V {
        blob_id: "0000000000000000000000000000000000000000000000000000000000000000",
        size: 0,
        encoding_type: 0,
        storage_epochs: 5,
        deadline: 0,
        sender: "0000000000000000000000000000000000000000",
        nonce: 0,
        commitment: "00000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000",
        intent_id: "0fe90843b2ea90fb6b0952a72fb1cbab1875821768640b5a7955aed434ac08f2",
    },
    V {
        blob_id: "abababababababababababababababababababababababababababababababab",
        size: 1024,
        encoding_type: 1,
        storage_epochs: 5,
        deadline: 1760000000,
        sender: "00112233445566778899aabbccddeeff00112233",
        nonce: 7,
        commitment: "abababababababababababababababababababababababababababababababab0000040001000000050000000068e77800",
        intent_id: "70286217803b49a342aa1ad3de24977ea30ff17ab3654e2aa8957e1a9cf799c9",
    },
    V {
        blob_id: "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
        size: 1,
        encoding_type: 2,
        storage_epochs: 10,
        deadline: 1234567890,
        sender: "cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe",
        nonce: 1,
        commitment: "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef00000001020000000a00000000499602d2",
        intent_id: "58564b85f5eeb8341134919fc24d54b4a6df32f86bf579cadbd1bcb131b8bb17",
    },
    V {
        blob_id: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        size: 4294967295,
        encoding_type: 255,
        storage_epochs: 4294967295,
        deadline: 18446744073709551615,
        sender: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        nonce: 18446744073709551615,
        commitment: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        intent_id: "43ca9d53e5a7adbcb88a9f1be9258336fe0e4d9ad25f51dfbd100b126f4e8f97",
    },
];

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap())
        .collect()
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

#[test]
fn parity_vectors_match() {
    for v in VECTORS {
        let mut blob_id = [0u8; 32];
        blob_id.copy_from_slice(&unhex(v.blob_id));
        let c = Commitment {
            blob_id,
            size: v.size,
            encoding_type: v.encoding_type,
            storage_epochs: v.storage_epochs,
            deadline: v.deadline,
        };
        assert_eq!(hex(&encode(&c)), v.commitment, "commitment mismatch");
        assert_eq!(
            hex(&derive_intent_id(&c, &unhex(v.sender), v.nonce)),
            v.intent_id,
            "intentId mismatch"
        );
    }
}
