// @generated by sdk/scripts/gen-parity-vectors.ts -- DO NOT EDIT.
// Cross-chain parity vectors for bosphor_lz::commitment_codec.
#[test_only]
module bosphor_lz::commitment_vectors;

public struct Vector has copy, drop {
    name: vector<u8>,
    blob_id: vector<u8>,
    size: u32,
    encoding_type: u8,
    storage_epochs: u32,
    deadline: u64,
    sender: vector<u8>,
    nonce: u64,
    commitment: vector<u8>,
    intent_id: vector<u8>,
}

public fun blob_id(v: &Vector): vector<u8> { v.blob_id }
public fun size(v: &Vector): u32 { v.size }
public fun encoding_type(v: &Vector): u8 { v.encoding_type }
public fun storage_epochs(v: &Vector): u32 { v.storage_epochs }
public fun deadline(v: &Vector): u64 { v.deadline }
public fun sender(v: &Vector): vector<u8> { v.sender }
public fun nonce(v: &Vector): u64 { v.nonce }
public fun commitment(v: &Vector): vector<u8> { v.commitment }
public fun intent_id(v: &Vector): vector<u8> { v.intent_id }

/// A full-length commitment whose version byte is not a supported version.
/// Every decoder must reject it.
public struct InvalidVector has copy, drop {
    name: vector<u8>,
    version: u8,
    commitment: vector<u8>,
}

public fun invalid_name(v: &InvalidVector): vector<u8> { v.name }
public fun invalid_version(v: &InvalidVector): u8 { v.version }
public fun invalid_commitment(v: &InvalidVector): vector<u8> { v.commitment }

public fun all(): vector<Vector> {
    let mut v = vector::empty<Vector>();
    v.push_back(Vector {
        name: b"all_zero",
        blob_id: x"0000000000000000000000000000000000000000000000000000000000000000",
        size: 0,
        encoding_type: 0,
        storage_epochs: 0,
        deadline: 0,
        sender: x"0000000000000000000000000000000000000000000000000000000000000000",
        nonce: 0,
        commitment: x"0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        intent_id: x"a4f556b8070855da3e9bfc0116ab844ef964254b9516f31df26d980ad8a6b74a",
    });
    v.push_back(Vector {
        name: b"default_epochs_evm_zero_sender",
        blob_id: x"0000000000000000000000000000000000000000000000000000000000000000",
        size: 0,
        encoding_type: 0,
        storage_epochs: 5,
        deadline: 0,
        sender: x"0000000000000000000000000000000000000000",
        nonce: 0,
        commitment: x"0100000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000",
        intent_id: x"77d74d8839cfef65e97c4619989a5cd3ffb1b8b0e142825b8270e1bf8aded8c7",
    });
    v.push_back(Vector {
        name: b"canonical_evm",
        blob_id: x"abababababababababababababababababababababababababababababababab",
        size: 1024,
        encoding_type: 1,
        storage_epochs: 5,
        deadline: 1760000000,
        sender: x"00112233445566778899aabbccddeeff00112233",
        nonce: 7,
        commitment: x"01abababababababababababababababababababababababababababababababab0000040001000000050000000068e77800",
        intent_id: x"7827b0f7e14c906b545f8bc961cc4ccad1f73ba2b68461b12df0a49fa8f6bb25",
    });
    v.push_back(Vector {
        name: b"sui_sender",
        blob_id: x"deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
        size: 1,
        encoding_type: 2,
        storage_epochs: 10,
        deadline: 1234567890,
        sender: x"cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe",
        nonce: 1,
        commitment: x"01deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef00000001020000000a00000000499602d2",
        intent_id: x"d992b1e321ffe9439081c607dfe780265eb9bf2e185a28b6e120876fe25bec47",
    });
    v.push_back(Vector {
        name: b"max_fields",
        blob_id: x"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        size: 4294967295,
        encoding_type: 255,
        storage_epochs: 4294967295,
        deadline: 18446744073709551615,
        sender: x"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        nonce: 18446744073709551615,
        commitment: x"01ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        intent_id: x"6acabe660433db2f3c7e16b0a65e673cfcd59b0a427c3ba0f85e72571cc8129c",
    });
    v
}

public fun invalid_all(): vector<InvalidVector> {
    let mut v = vector::empty<InvalidVector>();
    v.push_back(InvalidVector {
        name: b"unsupported_version_0",
        version: 0,
        commitment: x"00abababababababababababababababababababababababababababababababab0000040001000000050000000068e77800",
    });
    v.push_back(InvalidVector {
        name: b"unsupported_version_2",
        version: 2,
        commitment: x"02abababababababababababababababababababababababababababababababab0000040001000000050000000068e77800",
    });
    v
}
