// @generated by sdk/scripts/gen-parity-vectors.ts -- DO NOT EDIT.
// Cross-chain parity vectors for bosphor_lz::commitment_codec.
#[test_only]
module bosphor_lz::commitment_vectors;

public struct Vector has copy, drop {
    name: vector<u8>,
    blob_id: vector<u8>,
    size: u32,
    encoding_type: u8,
    storage_epochs: u32,
    deadline: u64,
    sender: vector<u8>,
    nonce: u64,
    commitment: vector<u8>,
    intent_id: vector<u8>,
}

public fun blob_id(v: &Vector): vector<u8> { v.blob_id }
public fun size(v: &Vector): u32 { v.size }
public fun encoding_type(v: &Vector): u8 { v.encoding_type }
public fun storage_epochs(v: &Vector): u32 { v.storage_epochs }
public fun deadline(v: &Vector): u64 { v.deadline }
public fun sender(v: &Vector): vector<u8> { v.sender }
public fun nonce(v: &Vector): u64 { v.nonce }
public fun commitment(v: &Vector): vector<u8> { v.commitment }
public fun intent_id(v: &Vector): vector<u8> { v.intent_id }

public fun all(): vector<Vector> {
    let mut v = vector::empty<Vector>();
    v.push_back(Vector {
        name: b"all_zero",
        blob_id: x"0000000000000000000000000000000000000000000000000000000000000000",
        size: 0,
        encoding_type: 0,
        storage_epochs: 0,
        deadline: 0,
        sender: x"0000000000000000000000000000000000000000000000000000000000000000",
        nonce: 0,
        commitment: x"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        intent_id: x"496e418294117864002a95f894a01c9cc414c86e17325489a5ea2f0eef181967",
    });
    v.push_back(Vector {
        name: b"default_epochs_evm_zero_sender",
        blob_id: x"0000000000000000000000000000000000000000000000000000000000000000",
        size: 0,
        encoding_type: 0,
        storage_epochs: 5,
        deadline: 0,
        sender: x"0000000000000000000000000000000000000000",
        nonce: 0,
        commitment: x"00000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000",
        intent_id: x"0fe90843b2ea90fb6b0952a72fb1cbab1875821768640b5a7955aed434ac08f2",
    });
    v.push_back(Vector {
        name: b"canonical_evm",
        blob_id: x"abababababababababababababababababababababababababababababababab",
        size: 1024,
        encoding_type: 1,
        storage_epochs: 5,
        deadline: 1760000000,
        sender: x"00112233445566778899aabbccddeeff00112233",
        nonce: 7,
        commitment: x"abababababababababababababababababababababababababababababababab0000040001000000050000000068e77800",
        intent_id: x"70286217803b49a342aa1ad3de24977ea30ff17ab3654e2aa8957e1a9cf799c9",
    });
    v.push_back(Vector {
        name: b"sui_sender",
        blob_id: x"deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
        size: 1,
        encoding_type: 2,
        storage_epochs: 10,
        deadline: 1234567890,
        sender: x"cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe",
        nonce: 1,
        commitment: x"deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef00000001020000000a00000000499602d2",
        intent_id: x"58564b85f5eeb8341134919fc24d54b4a6df32f86bf579cadbd1bcb131b8bb17",
    });
    v.push_back(Vector {
        name: b"max_fields",
        blob_id: x"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        size: 4294967295,
        encoding_type: 255,
        storage_epochs: 4294967295,
        deadline: 18446744073709551615,
        sender: x"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        nonce: 18446744073709551615,
        commitment: x"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        intent_id: x"43ca9d53e5a7adbcb88a9f1be9258336fe0e4d9ad25f51dfbd100b126f4e8f97",
    });
    v
}
